the second part of Accont page
GSG-CF04/foodApp3 pull request #16
Opened 2021-10-24 05:38 UTC by husamkamal

Relates #12

2021-10-24 07:05 UTC, IsraaAmani submitted a review, later dismissed

2021-10-25 04:29 UTC, yaqootturman requested changes

2021-10-25 04:29 UTC, yaqootturman commented on Account/index.html
> +        <section class="button">
use a descriptive class name, pleasse!

2021-10-25 04:29 UTC, yaqootturman commented on Account/index.html
> +            <article class="div1">
Its not cool way to use order for naming such as div1, div2 ....
and same for others hr1....

2021-10-25 04:29 UTC, yaqootturman commented on Account/style.css
> +body{
Do you need to add responsive part?

2021-10-25 06:00 UTC, husamkamal commented on Account/style.css
> +body{
I have added it

2021-10-25 06:38 UTC, yaqootturman requested changes

2021-10-25 06:38 UTC, yaqootturman commented on Account/style.css
> +@media  (min-width:500px) and (max-width:599) {
why using this width?
we have tablet and desktop width already

2021-10-25 06:38 UTC, yaqootturman commented on Account/style.css
> +@media  (min-width:800px) and (max-width:1024px) {
the images become pixel and not responsive in desktop and tablet size

2021-10-25 06:38 UTC, yaqootturman commented on Account/index.html
> +        <section class="button">
same

2021-10-25 13:42 UTC, IsraaAmani submitted a review, later dismissed

2021-10-25 16:14 UTC, yaqootturman approved these changes

2021-10-25 16:36 UTC, IsraaAmani approved these changes

2021-10-25 16:37 UTC, merged